spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-server-db            # Database URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mindfire
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: auth-service

     # Rabbitmq setup
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: amigo_vhost
    username: amigo
    password: amigo
    
server:
  port: 8765
