spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
      - id: addressModule
        uri: lb://ADDRESS-SERVICE
        predicates:
        - Path=/address/**
      - id: authServer
        uri: lb://AUTH-SERVER
        predicates:
        - Path=/auth-server/**
          
