server:
  port: 8762

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-db            # Database URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mindfire
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    

    # Rabbitmq setup         
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: amigo_vhost
    username: amigo
    password: amigo