
# For mail service
spring:       
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: amigo_vhost
    username: amigo
    password: amigo
  mail:
    host: smtp.gmail.com
    port: 587
    username: amigo.shoppe20@gmail.com
    password: amigo20@
    logging: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

  # Rabbitmq setup  

